### PR TITLE
Configuration and Sessions

### LINKED ISSUE #102: Initial configuration import
Now that we can export configurations (#62), we should be able to import them as well.

### LINKED ISSUE #136: changing the config of one track makes other tracks rerender
to reproduce: at startup with our current default configurations, open the config editor for the reference sequence track and change rendering.height.  You will see the wiggle and alignments tracks re-render, but they should not.

### LINKED ISSUE #145: sessions and defaultSession
We need the concept of a session, which is a partial state snapshot that doesn't include configuration, but includes the views and stuff that are open at a given time.

The root configuration should also have a non-editable `defaultSession` that has this state snapshot, which is what is initially loaded when the browser is shown, if there is not some other active session.

We will probably eventually be persisting sessions in localstorage, but that isn't in scope for this issue.

### LINKED ISSUE #192: Be able to define adapter capabilities
Need to know if an adapter can i.e. fetch sequences, features, aliases, etc.

Probably just a static array on the adapter class that defines a list of these (keep a master list somewhere?)

### PR DESCRIPTION
**Pull request by garrettjstevens**
Converts JBrowse to a React component and enables switching among multiple configs (each with a defaultSession) defined either in a file or as an object.

Adds the ability to define a reference sequence source (2bit, fasta, or sizes as an object) to an assembly, and views using that assembly will automatically use that for their displayed regions.

resolves #102
resolves #136
resolves #145
resolves #192

### CODE REVIEW

**Comment by garrettjstevens** [comment]
I think I finally feel good (enough) about this PR. Should be good to review/merge.

File: packages/jbrowse-web/src/mst-types.js [hunk 1]
```diff
@@ -24,7 +23,6 @@ export const PropTypes = {
 
 export const Region = types
   .model('Region', {
-    assemblyName: types.string,
```
Comment (rbuels) [inline packages/jbrowse-web/src/mst-types.js]: you sure we don't want assemblyName in a region anymore? I could see this eventually leading to problems when there are a couple different assemblies in play that have the same chromosome names.

File: packages/jbrowse-web/src/plugins/LinearGenomeView/models/index.js [hunk 2]
```diff
@@ -102,7 +100,22 @@ export default function LinearGenomeViewStateFactory(pluginManager) {
...
+      displayedRegions: [],
+    }))
     .actions(self => ({
+      afterAttach() {
+        const displayedRegionsDisposer = autorun(() => {
+          const { assemblyManager } = getRoot(self)
+          if (assemblyManager)
+            self.setDisplayedRegions(assemblyManager.displayedRegions)
+        })
+
```
Comment (rbuels) [inline packages/jbrowse-web/src/plugins/LinearGenomeView/models/index.js]: This is very problematic, because it means that all linear genome views are forced to show the same set of regions now. We can merge this in the interest of avoiding long-lived branches, but it will need to change very soon.

File: packages/jbrowse-web/src/plugins/LinearGenomeView/models/index.js [hunk 3]
```diff
@@ -102,7 +100,22 @@ export default function LinearGenomeViewStateFactory(pluginManager) {
         return getConf(self, 'reversed')
       },
     }))
+    .volatile(() => ({
+      displayedRegions: [],
```
Comment (rbuels) [inline packages/jbrowse-web/src/plugins/LinearGenomeView/models/index.js]: do you really think displayedRegions should really be volatile? we probably would want to save it so people can get back to what they were viewing

File: packages/jbrowse-web/src/plugins/LinearGenomeView/models/index.js (hunk 2 above)
Comment (rbuels) [reply packages/jbrowse-web/src/plugins/LinearGenomeView/models/index.js]: I think if we just move this "binding" of the view to an assembly to the root model, that would remove most of my concern.

File: packages/jbrowse-web/src/managers/AssemblyManager.js [hunk 4]
```diff
@@ -0,0 +1,131 @@
...
+              adapterConfig,
+            },
+            { timeout: 1000000 },
+          )),
+        )
+      } catch (error) {
+        console.error('Failed to fetch sequence', error)
+      }
+    }
+    this.displayedRegions = regions
```
[the remark this answers is not in the document]
Comment (garrettjstevens) [reply packages/jbrowse-web/src/managers/AssemblyManager.js]: Good point. The naming was kind of all over the place in this file, so I just added some changes that hopefully fixes things.

File: packages/jbrowse-web/src/plugins/LinearGenomeView/models/index.js (hunk 2 above)
Comment (garrettjstevens) [reply packages/jbrowse-web/src/plugins/LinearGenomeView/models/index.js]: Agreed, there needs to be something else that manages the displayed regions. Like I mentioned on gitter, maybe a RegionManager? It needs to be able to pull regions from several potential sources (assembly, config, regions file, user interaction, etc.) and keep track of which one is being used.

File: packages/jbrowse-web/src/mst-types.js (hunk 1 above)
Comment (garrettjstevens) [reply packages/jbrowse-web/src/mst-types.js]: I've thought a lot about this, and I still stick with what I did here. I also took assemblyName out of the adapters, since really there is nothing inherent about a data source that defines an assembly. You can say a data source is for a particular assembly, but it's not actually encoded in the file/config/other source. I ran into weird things like trying to use an adapter in an assembly config where defining an assembly name didn't make sense.

Likewise the view shouldn't need to know the assembly, since you might want to display the same Region of several closely related assemblies in the same view.

I think the track needs to manage the assembly. That way you can still have multiple assemblies with the same chromosome names, and each track will just handle them in the way it needs for that assembly. And if you want multiple assemblies in one track, you can use subtracks.

File: packages/jbrowse-web/src/plugins/LinearGenomeView/models/index.js (hunk 3 above)
Comment (garrettjstevens) [reply packages/jbrowse-web/src/plugins/LinearGenomeView/models/index.js]: I see this as getting moved to whatever we decide is going to keep track of the displayed regions (#197).

**Comment by garrettjstevens** [comment]
Opened #197 to address some shortcomings of this PR.

File: packages/jbrowse-web/src/plugins/LinearGenomeView/models/index.js (hunk 2 above)
Comment (rbuels) [reply packages/jbrowse-web/src/plugins/LinearGenomeView/models/index.js]: Maybe a ViewManager, which would be where we will put our logic for managing what views are shown, what kind of views they are, what regions they are showing, etc.

Because we are going to have a lot more kinds of views besides just LinearGenomeViews, and they will each

File: packages/jbrowse-web/src/mst-types.js (hunk 1 above)
Comment (rbuels) [reply packages/jbrowse-web/src/mst-types.js]: what about the case where we want critter:chr1 displayed next to human:chr1 in the same lineargenomeview? The lineargenomeview would not be able to tell the difference between them
