### PR TITLE
Fixes bug on URL highlight param in which refName aliases were not working

### LINKED ISSUE #4261: URL highlight does not appear with refName aliases
works
https://jbrowse.org/code/jb2/main/?config=test_data%2Fconfig_demo.json&assembly=hg19&loc=1:1,937,214..2,081,004&highlight=1:2,000,000-2,100,000&tracks=repeats_hg19

doesn't 
https://jbrowse.org/code/jb2/main/?config=test_data%2Fconfig_demo.json&assembly=hg19&loc=1:1,937,214..2,081,004&highlight=chr1:2,000,000-2,100,000&tracks=repeats_hg19

### PR DESCRIPTION
**Pull request by carolinebridge-oicr**
Fixes #4261 

works
https://s3.amazonaws.com/jbrowse.org/code/jb2/fix-ref-name-highlight/index.html?config=test_data%2Fconfig_demo.json&assembly=hg19&loc=1:1,937,214..2,081,004&highlight=1:2,000,000-2,100,000&tracks=repeats_hg19

works
https://s3.amazonaws.com/jbrowse.org/code/jb2/fix-ref-name-highlight/index.html?config=test_data%2Fconfig_demo.json&assembly=hg19&loc=1:1,937,214..2,081,004&highlight=chr1:2,000,000-2,100,000&tracks=repeats_hg19

### CODE REVIEW

File: plugins/linear-genome-view/src/LaunchLinearGenomeView/index.ts [hunk 1]
```diff
@@ -61,11 +61,19 @@ export default (pluginManager: PluginManager) => {
...
-          const location = parseLocString(highlight, refName =>
+          const parsedLocString = parseLocString(highlight, refName =>
             isValidRefName(refName, assembly),
           ) as Required<ParsedLocString>
+
+          const location = {
+            ...parsedLocString,
+            assemblyName: assembly,
+            refName:
+              asm.getCanonicalRefName(parsedLocString.refName) ??
```
Comment (cmdcolin) [inline plugins/linear-genome-view/src/LaunchLinearGenomeView/index.ts:72]: could consider moving this "asm.getCanonicalRefName(parsedLocString.refName) ?? parsedLocString.refName," to time of usage (e.g. in Highlight.tsx, OverviewHighlight.tsx) rather than data loading time. it is a little more laborious, but would handle cases that don't go through the launchlineargenomeview pathway for whatever reason

File: plugins/linear-genome-view/src/LinearGenomeView/components/Highlight.tsx [hunk 2]
```diff
@@ -95,7 +96,16 @@ const Highlight = observer(function Highlight({ model }: { model: LGV }) {
       : undefined
   }
 
-  const h = mapCoords(model.highlight)
+  const asm = assemblyManager.assemblies.find(
```
Comment (cmdcolin) [inline plugins/linear-genome-view/src/LinearGenomeView/components/Highlight.tsx:99]: can use `assemblyManager.get(model.highlight.assemblyName)` instead of find here
